# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lootbox.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlootbox.proto\x12)accelbyte.platform.entitlement.lootbox.v1\"\x9e\x01\n\x19RollLootBoxRewardsRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12L\n\x08itemInfo\x18\x04 \x01(\x0b\x32:.accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo\"f\n\x1aRollLootBoxRewardsResponse\x12H\n\x07rewards\x18\x01 \x03(\x0b\x32\x37.accelbyte.platform.entitlement.lootbox.v1.RewardObject\">\n\x0cRewardObject\x12\x0e\n\x06itemId\x18\x01 \x01(\t\x12\x0f\n\x07itemSku\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"\xca\x02\n\x0fLootBoxItemInfo\x12\x0e\n\x06itemId\x18\x01 \x01(\t\x12\x0f\n\x07itemSku\x18\x02 \x01(\t\x12\x13\n\x0brewardCount\x18\x03 \x01(\x05\x12\x66\n\x0elootBoxRewards\x18\x04 \x03(\x0b\x32N.accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.LootBoxRewardObject\x1a\x98\x01\n\x13LootBoxRewardObject\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12G\n\x05items\x18\x03 \x03(\x0b\x32\x38.accelbyte.platform.entitlement.lootbox.v1.BoxItemObject\x12\x0e\n\x06weight\x18\x04 \x01(\x05\x12\x0c\n\x04odds\x18\x05 \x01(\x01\"?\n\rBoxItemObject\x12\x0e\n\x06itemId\x18\x01 \x01(\t\x12\x0f\n\x07itemSku\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x32\xad\x01\n\x07LootBox\x12\xa1\x01\n\x12RollLootBoxRewards\x12\x44.accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsRequest\x1a\x45.accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsResponseB\x9a\x01\n-net.accelbyte.platform.entitlement.lootbox.v1B\x0clootBoxProtoP\x01Z-accelbyte.net/platform/entitlement/lootbox_v1\xaa\x02)Accelbyte.Platform.Entitlement.Lootbox.V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lootbox_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n-net.accelbyte.platform.entitlement.lootbox.v1B\014lootBoxProtoP\001Z-accelbyte.net/platform/entitlement/lootbox_v1\252\002)Accelbyte.Platform.Entitlement.Lootbox.V1'
  _ROLLLOOTBOXREWARDSREQUEST._serialized_start=61
  _ROLLLOOTBOXREWARDSREQUEST._serialized_end=219
  _ROLLLOOTBOXREWARDSRESPONSE._serialized_start=221
  _ROLLLOOTBOXREWARDSRESPONSE._serialized_end=323
  _REWARDOBJECT._serialized_start=325
  _REWARDOBJECT._serialized_end=387
  _LOOTBOXITEMINFO._serialized_start=390
  _LOOTBOXITEMINFO._serialized_end=720
  _LOOTBOXITEMINFO_LOOTBOXREWARDOBJECT._serialized_start=568
  _LOOTBOXITEMINFO_LOOTBOXREWARDOBJECT._serialized_end=720
  _BOXITEMOBJECT._serialized_start=722
  _BOXITEMOBJECT._serialized_end=785
  _LOOTBOX._serialized_start=788
  _LOOTBOX._serialized_end=961
# @@protoc_insertion_point(module_scope)
