# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lootbox_pb2 as lootbox__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lootbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LootBoxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RollLootBoxRewards = channel.unary_unary(
                '/accelbyte.platform.entitlement.lootbox.v1.LootBox/RollLootBoxRewards',
                request_serializer=lootbox__pb2.RollLootBoxRewardsRequest.SerializeToString,
                response_deserializer=lootbox__pb2.RollLootBoxRewardsResponse.FromString,
                _registered_method=True)


class LootBoxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RollLootBoxRewards(self, request, context):
        """*
        RollLootBoxRewards
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LootBoxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RollLootBoxRewards': grpc.unary_unary_rpc_method_handler(
                    servicer.RollLootBoxRewards,
                    request_deserializer=lootbox__pb2.RollLootBoxRewardsRequest.FromString,
                    response_serializer=lootbox__pb2.RollLootBoxRewardsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.platform.entitlement.lootbox.v1.LootBox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelbyte.platform.entitlement.lootbox.v1.LootBox', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LootBox(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RollLootBoxRewards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.platform.entitlement.lootbox.v1.LootBox/RollLootBoxRewards',
            lootbox__pb2.RollLootBoxRewardsRequest.SerializeToString,
            lootbox__pb2.RollLootBoxRewardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
