# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.proto import lootbox_pb2 as app_dot_proto_dot_lootbox__pb2


class LootBoxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RollLootBoxRewards = channel.unary_unary(
                '/accelbyte.platform.entitlement.lootbox.v1.LootBox/RollLootBoxRewards',
                request_serializer=app_dot_proto_dot_lootbox__pb2.RollLootBoxRewardsRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_lootbox__pb2.RollLootBoxRewardsResponse.FromString,
                )


class LootBoxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RollLootBoxRewards(self, request, context):
        """*
        RollLootBoxRewards
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LootBoxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RollLootBoxRewards': grpc.unary_unary_rpc_method_handler(
                    servicer.RollLootBoxRewards,
                    request_deserializer=app_dot_proto_dot_lootbox__pb2.RollLootBoxRewardsRequest.FromString,
                    response_serializer=app_dot_proto_dot_lootbox__pb2.RollLootBoxRewardsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.platform.entitlement.lootbox.v1.LootBox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LootBox(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RollLootBoxRewards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.platform.entitlement.lootbox.v1.LootBox/RollLootBoxRewards',
            app_dot_proto_dot_lootbox__pb2.RollLootBoxRewardsRequest.SerializeToString,
            app_dot_proto_dot_lootbox__pb2.RollLootBoxRewardsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
