# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/lootbox.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/proto/lootbox.proto',
  package='accelbyte.platform.entitlement.lootbox.v1',
  syntax='proto3',
  serialized_options=b'\n-net.accelbyte.platform.entitlement.lootbox.v1B\014lootBoxProtoP\001Z-accelbyte.net/platform/entitlement/lootbox_v1\252\002)Accelbyte.Platform.Entitlement.Lootbox.V1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x61pp/proto/lootbox.proto\x12)accelbyte.platform.entitlement.lootbox.v1\"\x9e\x01\n\x19RollLootBoxRewardsRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12L\n\x08itemInfo\x18\x04 \x01(\x0b\x32:.accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo\"f\n\x1aRollLootBoxRewardsResponse\x12H\n\x07rewards\x18\x01 \x03(\x0b\x32\x37.accelbyte.platform.entitlement.lootbox.v1.RewardObject\">\n\x0cRewardObject\x12\x0e\n\x06itemId\x18\x01 \x01(\t\x12\x0f\n\x07itemSku\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"\xca\x02\n\x0fLootBoxItemInfo\x12\x0e\n\x06itemId\x18\x01 \x01(\t\x12\x0f\n\x07itemSku\x18\x02 \x01(\t\x12\x13\n\x0brewardCount\x18\x03 \x01(\x05\x12\x66\n\x0elootBoxRewards\x18\x04 \x03(\x0b\x32N.accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.LootBoxRewardObject\x1a\x98\x01\n\x13LootBoxRewardObject\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12G\n\x05items\x18\x03 \x03(\x0b\x32\x38.accelbyte.platform.entitlement.lootbox.v1.BoxItemObject\x12\x0e\n\x06weight\x18\x04 \x01(\x05\x12\x0c\n\x04odds\x18\x05 \x01(\x01\"?\n\rBoxItemObject\x12\x0e\n\x06itemId\x18\x01 \x01(\t\x12\x0f\n\x07itemSku\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x32\xad\x01\n\x07LootBox\x12\xa1\x01\n\x12RollLootBoxRewards\x12\x44.accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsRequest\x1a\x45.accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsResponseB\x9a\x01\n-net.accelbyte.platform.entitlement.lootbox.v1B\x0clootBoxProtoP\x01Z-accelbyte.net/platform/entitlement/lootbox_v1\xaa\x02)Accelbyte.Platform.Entitlement.Lootbox.V1b\x06proto3'
)




_ROLLLOOTBOXREWARDSREQUEST = _descriptor.Descriptor(
  name='RollLootBoxRewardsRequest',
  full_name='accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsRequest.namespace', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsRequest.quantity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemInfo', full_name='accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsRequest.itemInfo', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=229,
)


_ROLLLOOTBOXREWARDSRESPONSE = _descriptor.Descriptor(
  name='RollLootBoxRewardsResponse',
  full_name='accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rewards', full_name='accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsResponse.rewards', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=333,
)


_REWARDOBJECT = _descriptor.Descriptor(
  name='RewardObject',
  full_name='accelbyte.platform.entitlement.lootbox.v1.RewardObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemId', full_name='accelbyte.platform.entitlement.lootbox.v1.RewardObject.itemId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemSku', full_name='accelbyte.platform.entitlement.lootbox.v1.RewardObject.itemSku', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='accelbyte.platform.entitlement.lootbox.v1.RewardObject.count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=397,
)


_LOOTBOXITEMINFO_LOOTBOXREWARDOBJECT = _descriptor.Descriptor(
  name='LootBoxRewardObject',
  full_name='accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.LootBoxRewardObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.LootBoxRewardObject.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.LootBoxRewardObject.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='items', full_name='accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.LootBoxRewardObject.items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight', full_name='accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.LootBoxRewardObject.weight', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='odds', full_name='accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.LootBoxRewardObject.odds', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=578,
  serialized_end=730,
)

_LOOTBOXITEMINFO = _descriptor.Descriptor(
  name='LootBoxItemInfo',
  full_name='accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemId', full_name='accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.itemId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemSku', full_name='accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.itemSku', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rewardCount', full_name='accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.rewardCount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lootBoxRewards', full_name='accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.lootBoxRewards', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LOOTBOXITEMINFO_LOOTBOXREWARDOBJECT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=730,
)


_BOXITEMOBJECT = _descriptor.Descriptor(
  name='BoxItemObject',
  full_name='accelbyte.platform.entitlement.lootbox.v1.BoxItemObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemId', full_name='accelbyte.platform.entitlement.lootbox.v1.BoxItemObject.itemId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemSku', full_name='accelbyte.platform.entitlement.lootbox.v1.BoxItemObject.itemSku', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='accelbyte.platform.entitlement.lootbox.v1.BoxItemObject.count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=732,
  serialized_end=795,
)

_ROLLLOOTBOXREWARDSREQUEST.fields_by_name['itemInfo'].message_type = _LOOTBOXITEMINFO
_ROLLLOOTBOXREWARDSRESPONSE.fields_by_name['rewards'].message_type = _REWARDOBJECT
_LOOTBOXITEMINFO_LOOTBOXREWARDOBJECT.fields_by_name['items'].message_type = _BOXITEMOBJECT
_LOOTBOXITEMINFO_LOOTBOXREWARDOBJECT.containing_type = _LOOTBOXITEMINFO
_LOOTBOXITEMINFO.fields_by_name['lootBoxRewards'].message_type = _LOOTBOXITEMINFO_LOOTBOXREWARDOBJECT
DESCRIPTOR.message_types_by_name['RollLootBoxRewardsRequest'] = _ROLLLOOTBOXREWARDSREQUEST
DESCRIPTOR.message_types_by_name['RollLootBoxRewardsResponse'] = _ROLLLOOTBOXREWARDSRESPONSE
DESCRIPTOR.message_types_by_name['RewardObject'] = _REWARDOBJECT
DESCRIPTOR.message_types_by_name['LootBoxItemInfo'] = _LOOTBOXITEMINFO
DESCRIPTOR.message_types_by_name['BoxItemObject'] = _BOXITEMOBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RollLootBoxRewardsRequest = _reflection.GeneratedProtocolMessageType('RollLootBoxRewardsRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROLLLOOTBOXREWARDSREQUEST,
  '__module__' : 'app.proto.lootbox_pb2'
  # @@protoc_insertion_point(class_scope:accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsRequest)
  })
_sym_db.RegisterMessage(RollLootBoxRewardsRequest)

RollLootBoxRewardsResponse = _reflection.GeneratedProtocolMessageType('RollLootBoxRewardsResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROLLLOOTBOXREWARDSRESPONSE,
  '__module__' : 'app.proto.lootbox_pb2'
  # @@protoc_insertion_point(class_scope:accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsResponse)
  })
_sym_db.RegisterMessage(RollLootBoxRewardsResponse)

RewardObject = _reflection.GeneratedProtocolMessageType('RewardObject', (_message.Message,), {
  'DESCRIPTOR' : _REWARDOBJECT,
  '__module__' : 'app.proto.lootbox_pb2'
  # @@protoc_insertion_point(class_scope:accelbyte.platform.entitlement.lootbox.v1.RewardObject)
  })
_sym_db.RegisterMessage(RewardObject)

LootBoxItemInfo = _reflection.GeneratedProtocolMessageType('LootBoxItemInfo', (_message.Message,), {

  'LootBoxRewardObject' : _reflection.GeneratedProtocolMessageType('LootBoxRewardObject', (_message.Message,), {
    'DESCRIPTOR' : _LOOTBOXITEMINFO_LOOTBOXREWARDOBJECT,
    '__module__' : 'app.proto.lootbox_pb2'
    # @@protoc_insertion_point(class_scope:accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.LootBoxRewardObject)
    })
  ,
  'DESCRIPTOR' : _LOOTBOXITEMINFO,
  '__module__' : 'app.proto.lootbox_pb2'
  # @@protoc_insertion_point(class_scope:accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo)
  })
_sym_db.RegisterMessage(LootBoxItemInfo)
_sym_db.RegisterMessage(LootBoxItemInfo.LootBoxRewardObject)

BoxItemObject = _reflection.GeneratedProtocolMessageType('BoxItemObject', (_message.Message,), {
  'DESCRIPTOR' : _BOXITEMOBJECT,
  '__module__' : 'app.proto.lootbox_pb2'
  # @@protoc_insertion_point(class_scope:accelbyte.platform.entitlement.lootbox.v1.BoxItemObject)
  })
_sym_db.RegisterMessage(BoxItemObject)


DESCRIPTOR._options = None

_LOOTBOX = _descriptor.ServiceDescriptor(
  name='LootBox',
  full_name='accelbyte.platform.entitlement.lootbox.v1.LootBox',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=798,
  serialized_end=971,
  methods=[
  _descriptor.MethodDescriptor(
    name='RollLootBoxRewards',
    full_name='accelbyte.platform.entitlement.lootbox.v1.LootBox.RollLootBoxRewards',
    index=0,
    containing_service=None,
    input_type=_ROLLLOOTBOXREWARDSREQUEST,
    output_type=_ROLLLOOTBOXREWARDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOOTBOX)

DESCRIPTOR.services_by_name['LootBox'] = _LOOTBOX

# @@protoc_insertion_point(module_scope)
